baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Auto Śimon'

author = "Stanislav Valášek"
copyright = "Copyright © 2021, Auto - Šimon, all rights reserved."

# Do not pluralize site sections
pluralizelisttitles = false

[permalinks]
   tags = "/novinky/:slug/"

[params]
    name = "Auto - Šimon"
    description = "Výkup a prodej aut. Dovoz osobních a užitkových aut převážně z Německa."

    favicon = "/logo.jpg"
    backgroundImage = "/images/banner.jpg"
    banner = "/banner.jpg"
    logo = "/logo.jpg"

# https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter
[build]
  writeStats = true